### ISSUE TITLE
Add an option to rebuild PR's even if it was already built

### ISSUE THREAD

**Issue by suryagaddipati** [groupon/DotCi#134]
Currently PR's are ignored if it was opened from the same repo. 
Consider adding a project option to rebuild when PR is opened.

**Comment by vvitayau** [comment]
it would be better to treat PR as PR whether from same repo or forked repo.
This way when the PR is closed and re-opened ... the build will re-initiate.

Currently this is not the case if PR is from within the same repo.
Even the build history view is different to indicate branch name instead of PR number when from 
within the same repo.

**Comment by daniel-beard** [comment]
Any update on this?

**Comment by suryagaddipati** [comment]
@daniel-beard slating this for release somepoint next week.

**Comment by suryagaddipati** [comment]
fixed this in `2.15.0`

**Comment by daniel-beard** [comment]
@suryagaddipati is this reflected in the UI as the "Build Pull Requests from the same Repository" option?

**Comment by suryagaddipati** [comment]
@daniel-beard yes
