### ISSUE TITLE
DotCI with docker compose 'before' steps

### ISSUE THREAD

**Issue by justicel** [groupon/DotCi#145]
Is there no way to define 'before' steps to run when you are using docker compose? I have a rails app and I need to be able to 'db:setup' before running rspec tests and I don't see any way in the documentation to do this.

**Comment by ppg** [comment]
Not to thread hijack, but along these lines I might be using docker compose to also bring up required external services, do tests, then shut down, so it'd be nice in general to have a way to specify multiple different docker compose commands but sequentially instead of in parallel. I think that's a super set of before, so hopefully there can be an extension that handles both cases.

**Comment by Dinoshauer** [comment]
I'd love to see this as well :)

**Comment by vvitayau** [comment]
resolved as-of https://github.com/groupon/DotCi/pull/174
