### ISSUE TITLE
DOTCI_PULL_REQUEST only works for forks

### ISSUE THREAD

**Issue by jkrems** [groupon/DotCi#194]
I'm assuming this is the case because of how the builds are triggered. It makes the feature not really useful for teams that work in branches instead of creating one fork per user.

**Comment by suryagaddipati** [comment]
Pull requests from within the same repo are not rebuilt since they were already build when branch was pushed to ci. 

There is a configuration option per Job called `Build Pull Requests from the same Repository` to override this behavior. 

Closing this issue since it is working as expected . Feel free to reopen it if I misunderstood the issue.

**Comment by jkrems** [comment]
Ah, thanks! Didn't know about that option.
